ApprovalTests/Namers/StackTraceParsers/StackTraceParser.cs
Small spelling mistake I found today while running tests.
=> Spelling mistake

ApprovalTests/ApprovalTests.nuspec
Note: I was reviewing the keywords in https://github.com/approvals/Approvals.NodeJS and wondered what was used in NuGet, noticed there wasn't any.
Also I'm guessing the xml is valid - but just edited this in GitHub, so not sure...
=> Adding some tags to nuspec file

ApprovalTests/Approvers/FileApprover.cs
On Mac OS X, FileApprover creates a received file with a slash in the file name. Also, it can not find the approved file.
=> Use Path.Combine to make a full file name

ApprovalTests.MachineSpecific.Tests/ApprovalTests.MachineSpecific.Tests.csproj, ApprovalTests.MachineSpecific.Tests/Namer/VisualStudioReporterTest.cs, ApprovalTests/Utilities/ParentProcessUtils.cs, ApprovalTests/WindowsRegistry/WindowsRegistryAssert.cs
- Use faster call with p/invoke (few ms compared to hundreds with performance counters)
- Try to avoid infinite loops because if the root parent process has died, one child could have re-used the root id, thus in the previous implementation leading to an infinite loop.
=> Speed improvements + fix sporadic infinite loops due to PID re-use in parent-child

ApprovalTests/ApprovalTests.nuspec
When I add ApprovalTests today, it always grabs an old version of ApprovalUtilities.
=> Make ApprovalTests depend on the corresponding ApprovalUtilities

ApprovalTests/Reporters/QuietReporter.cs
- Windows-R opens the Run dialog box. With `cmd /c` the command will work there.
- In PowerShell `move /Y` doesn't work, but with `cmd /c` it will work there, too.
=> Make clipboard reporter work from Run

ApprovalTests.Tests/ApprovalTests.Tests.csproj, ApprovalTests.Tests/Issues/CustomNamerShouldBeSubstitutable.approved.txt, ApprovalTests.Tests/Issues/CustomNamerShouldBeSubstitutableTest.cs, ApprovalTests/Approvals.cs
https://github.com/approvals/ApprovalTests.Net/issues/140
- Unittest showing issue when not calling Aprovals.SetCaller() with a custom IApprovalNamer.
- Fix in getting CurrentCaller by also garding for null in currentCaller.Value
=> Fix for issue #140

ApprovalTests/Wpf/WpfBindingsAssert.cs
While most test runners close the process when they're done, NCrunch keeps the process open, leaving the window visible on the desktop.
=> Close window after WPF assertion

ApprovalTests.Xunit/ApprovalTests.Xunit.csproj, ApprovalTests.Xunit/CompatibilityWithXunit2Tests.cs, ApprovalTests.Xunit2/ApprovalTests.Xunit2.csproj, ApprovalTests.Xunit2/CompatibilityWithXunit1Test.cs, ApprovalTests/Reporters/FrameworkAssertReporter.cs, ApprovalTests/Reporters/XUnit2Reporter.cs
Default configuration of `FrameworkAssertApproval` does not consider xunit2 at
all. As a result xunit2 tests are failing on continuous integration servers
because ApprovalTests handles them as xunit ones and tries to invoke missing
assert method. The error is the same as in #159.
Besides of making `FrameworkAssertApproval` aware of xunit2 I've added more
smartess to xunit2 reporter itself. Otherwise it conflicted with xunit.
=> Improve support of xunit2

ApprovalTests.Tests/Namer/ApprovalResultsTest.cs, ApprovalTests/Namers/StackTraceParsers/AttributeStackTraceParser.cs
Given a nested test class structure:
```csharp
[TestFixture]
public class Parent
{
[TestFixture]
public class Nested
{
[Test]
public void TestMethod()
{
}
}
}
```
The files would be named `Nested.TestMethod.*.*`
However if you have the same structure in a different class with the same nested class & test method naming, these file names would conflict.
So this will instead make the filename be `Parent.Nested.TestMethod.*.*`
=> Add parent class names to files written for nested classes

ApprovalTests.Tests/ApprovalTests.Tests.csproj, ApprovalTests.Tests/Set/SetTests.TestFile.approved.txt, ApprovalTests.Tests/Set/SetTests.TestFileWithScrubber.approved.txt, ApprovalTests.Tests/Set/SetTests.TestListObject.approved.txt, ApprovalTests.Tests/Set/SetTests.TestListString.approved.txt, ApprovalTests.Tests/Set/SetTests.cs, ApprovalTests.Tests/Set/a.txt, ApprovalTests/ApprovalTests.csproj, ApprovalTests/Set/SetApprovals.cs
I had a need to be able to run `VerifyFile()` on a log file in which the timestamps would be different each time and I couldn't guarantee the order of the log lines. So I wanted to be able to run a scrubber over each line to remove the timestamp and then to compare the lines regardless of order.
Where this led me was adding `VerifySet()` methods that correspond to `VerifyAll()`, the difference being that `VerifySet()` first sorts the incoming `IEnumerable`. The effect is that the order of the elements is normalized each time so that received can be compared to approved as a set, rather than as an ordered list.
Then I added versions of `VerifyFileAsSet()`, both with and without a scrubber, that treat a text file as `IEnumerable<string>` and call `VerifySet()`.
These are very useful to me …
=> Add set approvals

ApprovalTests/Reporters/GenericDiffReporter.cs, ApprovalTests/Utilities/TestCounter.cs, ApprovalUtilities.Tests/Utilities/PathUtilitiesTest.cs, ApprovalUtilities/Utilities/PathUtilities.cs
I happened to notice a misspelled method name; I marked it with Obsolete and added the correct spelling.
=> Fix misspelled method name

ApprovalTests.Tests/Namer/NunitStackTraceNamerTests.cs, ApprovalTests/Namers/StackTraceParsers/StackTraceParser.cs
Changing from .net standard to full framework with new csproj project requires the <DebugType>full</DebugType>
attribute to be added to the project.
=> B    add new error message for if a source path cannot be found

ApprovalTests/Namers/AssemblyLocationNamer.cs, ApprovalTests/Namers/UnitTestFrameworkNamer.cs
I had same problems as in #66, used just the namer from PR #71.
To use just call this in your test:
`Approvals.RegisterDefaultNamerCreation(() => new UnitTestFrameworkNamerAssemblyLocation());`
One limitation is that if your test is in a sub-folder you need a post-build copy to destination folder for example:
`copy /y $(ProjectDir)**subfolder**\*.approved.txt $(TargetDir)`
=> Add new namer that looks for approval files in same folder as assembly

ApprovalTests.Tests/Reporters/IntroductionReporterTest.TestComment.approved.txt
Even though it's not really treated as MarkDown, MD is still easier for humans to make sense of.
=> Wording and formatting of intro-to-approvals message

ApprovalTests.Tests/FileWithUtf8ByteOrderMark.txt, ApprovalTests.Tests/FileWithoutUtf8ByteOrderMark.txt, ApprovalTests.Tests/StringEncodingTest.cs, ApprovalTests/Writers/ApprovalTextWriter.cs
given this was 6 years ago https://github.com/approvals/ApprovalTests.Net/commit/d55f3313bbc4e79a7e84866bebe5945c50a9bf0a
and it is meant to be a one time thing. i think we can remove that code.
@isidore thoughts
=> B remove redundant DoUpgradeToUTF8Patch

docs/ApprovalTests/ReportersGettingStarted.md
There was a small typo in the word `bowser`.
Change `bowser` to `browser`.
=> d - Fix minor typo in docs

src/ApprovalTests.Tests/Core/SerializableExceptionsTest.cs, src/ApprovalTests/TheoryTests/SerializableTheory.cs
https://github.com/dotnet/designs/blob/main/accepted/2020/better-obsoletion/binaryformatter-obsoletion.md
=> Mark SerializableTheory as obsolete

src/ApprovalTests/ApprovalTests.csproj
Old minimum supported frameworks
* net462
* netstandard2.0
* net5.0
New 
* net472
* net6.0
=> update supported frameworks

src/ApprovalTests/ApprovalTests.csproj
M.W32.Registry has been inbox on .NET Framework since forever and in modern .NET starting with .NET 6. There's no need for the package reference anymore.
=> Remove Microsoft.Win32.Registry package dependency

src/ApprovalTests/Core/IApprover.cs
fix typo that misleads about call to `Approve()` and `Fail()`
`Fail()` actually invoked only if `Approve()` returns `false`
=> fix typo in IApprovalApprover description
