- ApprovalTests/ApprovalTests.csproj
- ApprovalTests/Reporters/BambooReporter.cs
- ApprovalTests/Reporters/DefaultFrontLoaderReporter.cs
Bamboo is Atlassian's CI build server (https://www.atlassian.com/software/bamboo) - in case anybody wasn't aware.
> Adds reporter for Bamboo

- ApprovalTests.MSTest/ApprovalTests.MSTest.csproj
- ApprovalTests.MSpec/ApprovalTests.MSpec.csproj
- ApprovalTests.MachineSpecific.Tests/ApprovalTests.MachineSpecific.Tests.csproj
- ApprovalTests.MbUnit/ApprovalTests.MbUnit.csproj
- ApprovalTests.Tests/ApprovalTests.Tests.csproj
- ApprovalTests.Xunit2/ApprovalTests.Xunit2.csproj
- ApprovalTests/ApprovalTests.csproj
- ApprovalUtilities.Net45/ApprovalUtilities.Net45.csproj
- ApprovalUtilities.Tests/ApprovalUtilities.Tests.csproj
- ApprovalUtilities/ApprovalUtilities.csproj
- ReportingDemo/ReportingDemo.csproj
Just being a boy scout, but I don't think these are necessary and are just noise now.
> Remove unused dependencies.

- ApprovalUtilities.Tests/Reflection/ReflectionUtilitiesTest.cs
- Move usings to outer as they don't seem necessary?
- White space obsessed
> No explicit need for TortoiseDiffReporter

- ApprovalTests/Reporters/KDiffReporter.cs
Fixes https://github.com/approvals/ApprovalTests.Net/issues/149 by passing the second argument as the merge output file.
> Merge changes into approved file when using KDiff

- ApprovalTests/ApprovalTests.csproj
- ApprovalTests/Reporters/DiffPrograms.cs
- ApprovalTests/Reporters/TortoiseDiffReporter.cs
- ApprovalTests/Reporters/TortoiseGitTextDiffReporter.cs
- ApprovalTests/Reporters/TortoiseTextDiffReporter.cs
As TortoiseMerge isn't working when only installed TortioseGit. 
Tested locally.
> Add support for TortoiseGitMerge as Reporter

- readme.md
two hyperlinks where looking strange
---
> Fix hyperlinks (markdown) in readme

- ApprovalTests.MsTestV2/NamerTest.MSTestV2DataTestMethod.ForScenario.MsDataTest.approved.txt
- ApprovalTests.MsTestV2/NamerTest.MSTestV2DataTestMethod.approved.txt
- ApprovalTests.MsTestV2/NamerTest.cs
> Fixes after review

- ApprovalTests/ApprovalTests.csproj
- ApprovalTests/Approvers/FileApprover.cs
- ApprovalTests/Email/EmailApprovals.cs
- ApprovalTests/Namers/ApprovalResults.cs
- ApprovalTests/Namers/StackTraceParsers/AttributeStackTraceParser.cs
- ApprovalTests/Namers/UnitTestFrameworkNamer.cs
- ApprovalTests/Reporters/AssertReporter.cs
- ApprovalTests/Reporters/DotNet4Utilities.cs
- ApprovalTests/Reporters/ExecutableQueryFailure.cs
- ApprovalTests/Reporters/GenericDiffReporter.cs
- ApprovalTests/Reporters/TortoiseComboImageReporter.cs
- ApprovalTests/Reporters/VisualStudioProjectFileAdder.cs
- ApprovalTests/Scrubber/PdfScrubber.cs
- ApprovalTests/Set/SetApprovals.cs
- ApprovalTests/Utilities/StringReporting.cs
- ApprovalTests/Utilities/TestCounter.cs
- ApprovalTests/Writers/ApprovalBinaryWriter.cs
- ApprovalTests/Writers/ApprovalTextWriter.cs
- ApprovalTests/Writers/ConfigurableTempTextFileWriter.cs
- ApprovalTests/Writers/ExistingFileWriter.cs
- ApprovalTests/packages.config
- ApprovalUtilities/ApprovalUtilities.csproj
- ApprovalUtilities/SimpleLogger/Writers/FileWriter.cs
- ApprovalUtilities/Utilities/FileUtilities.cs
- ApprovalUtilities/Utilities/OsUtils.cs
- ApprovalUtilities/Utilities/PathUtilities.cs
started using AlphaFS instead of System.IO to solve PathTooLongException problem
PathTooLongException (issue #199)
> AlphaFS without tests

- ApprovalUtilities/Utilities/ClipboardUtilities.cs
> use Clipboard.SetDataObject instead of Clipboard.SetText

- ApprovalUtilities/ApprovalUtilities.csproj
@isidore there is a System.Management nuget :)
replaces https://github.com/approvals/ApprovalTests.Net/tree/OsNames
> use System.Management nuget

- ApprovalUtilities/ApprovalUtilities.csproj
@isidore worked out why is wasnt building :)
> move ApprovalUtilities to netStandard

- ApprovalTests/ApprovalTests.csproj
- ApprovalTests/build/ApprovalTests.props
> default consuming project settings using a build/props file

- ApprovalTests/Reporters/ContinuousIntegration/MightyMooseAutoTestReporter.cs
- ApprovalTests/Reporters/ContinuousIntegration/TfsReporter.cs
- ApprovalTests/Utilities/ParentProcessUtils.cs
> B cache process names

- ApprovalTests.Tests/Reporters/ReporterFactoryTest.cs
- ApprovalTests/Namers/StackTraceParsers/AttributeStackTraceParser.cs
- ApprovalUtilities/CallStack/Caller.cs
- ApprovalUtilities/Reflection/ReflectionUtilities.cs
> B respect async when looking for reporters

- ApprovalTests/Namers/ApprovalResults.cs
- ApprovalTests/Namers/NamerFactory.cs
> R obsolete AsEnvironmentSpecificTest(Func<string> environmentLabeler)

- ApprovalTests/Reporters/ContinuousIntegration/MightyMooseAutoTestReporter.cs
> mark AutoTest as obsolete

- ApprovalTests/Reporters/ContinuousIntegration/CruiseControlNetReporter.cs
> R Mark Cruise Control support as obsolete

- docs/ApprovalTests/mdsource/readme.source.md
- docs/ApprovalTests/readme.md
> d Update docs

- src/ApprovalTests/ApprovalTests.csproj
> fix empty files ref

- src/ApprovalTests/Reporters/MachineSpecificReporter.cs
- src/ApprovalTests/Writers/ApprovalTextWriter.cs
> move to utf8 no bom

- docs/ApprovalTests/explanations/MainConcepts.md
Small pull requests are great and easy for me to understand and accept
Then you should setup a remote pairing session with Llewellyn ( llewellyn.falco@gmail.com )
Usually the sessions are between 45-90 minutes.
assuming you still feel it is small, please include
A description of what the PR achieves.
Outline the implementation.
Any tests that are affected.
I prefer lots of very small commits prefixed with [Arlo's git notation](https://github.com/RefactoringCombos/ArlosCommitNotation/blob/master/README.md)
> Fix typo in docs

- docs/ApprovalTests/ReportersGettingStarted.md
> Fix recent typo in docs

- docs/ApprovalTests/explanations/MainConcepts.md
> Fix recent typo in Main Concept docs

- src/ApprovalTests/Reporters/ContinuousIntegration/TeamCityReporter.cs
TeamCity are detected by _TEAMCITY_VERSION_ nevironment variable instead of _TEAMCITY_PROJECT_NAME_
> B!! It is better to use TEAMCITY_VERSION instead TEAMCITY_PROJECT_NAME
